name: amrvariant
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7.12
  - pip=21.3.1
  - bcftools=1.14
  - samtools=1.14
  - pandas=1.3.5
  - bowtie2=2.4.4
  - numpy=1.21.5
  - biopython=1.72
  - pip:
    - STAPAMRTime==0.0.1

